export const weatherInputType = {
  INPUT_CITY: 'INPUT_CITY',
  WEATHER_FETCH_REQUEST: 'WEATHER_FETCH_REQUEST',
  WEATHER_ASYNC_SUCCESS: 'WEATHER_ASYNC_SUCCESS',
  WEATHER_ASYNC_FAIL: 'WEATHER_ASYNC_FAIL'
}