export const weatherInputType = {
  INPUT_CITY: 'INPUT_CITY',
  WEATHER_ASYNC_START: 'WEATHER_ASYNC_START',
  WEATHER_ASYNC_SUCCESS: 'WEATHER_ASYNC_SUCCESS',
  WEATHER_ASYNC_FAIL: 'WEATHER_ASYNC_FAIL'
}